require 'rubygems'
require 'cucumber'
require 'cucumber/rake/task'

Cucumber::Rake::Task.new(:local) do |t|
  t.profile = 'default'
  t.cucumber_opts = "-f html --out results/test_report.html"
end

Cucumber::Rake::Task.new(:prod) do |t|
  t.profile = 'prod'
  t.cucumber_opts = "-f html --out results/test_report.html"
end

task :default => :local